# Deploy static sites to GitHub Pages with unified structure

name: Deploy NTU Student Resources to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Build unified site structure
        run: |
          mkdir -p public
          
          # Copy main page files
          cp v1/index.html public/
          cp v1/main-style.css public/
          
          # Copy Room Layout PowerPoint
          cp "v1/Room Layout.pptx" public/ || echo "Room Layout.pptx not found, skipping..."
          
          # Copy Clubs & Societies Explorer
          mkdir -p public/ntu-clubs
          cp -r "v1/NTU Clubs & Societies Explorer"/* public/ntu-clubs/
          
          # Copy Airport Guide with updated styling
          mkdir -p public/airport-guide
          cp -r "v1/Airport Guide/v2"/* public/airport-guide/
          
          # Update airport guide to use consistent styling
          if [ -f public/airport-guide/2-style.css ]; then
            mv public/airport-guide/2-style.css public/airport-guide/style.css
          fi
          if [ -f public/airport-guide/2-script.js ]; then
            mv public/airport-guide/2-script.js public/airport-guide/script.js
          fi
          if [ -f public/airport-guide/2-index.html ]; then
            mv public/airport-guide/2-index.html public/airport-guide/index.html
          fi
          
          # Add navigation link back to main page in airport guide
          if [ -f public/airport-guide/index.html ]; then
            sed -i '/<body>/a <a href="../index.html" class="main-nav-link"><i data-lucide="arrow-left"></i><span>Back to Hub</span></a>' public/airport-guide/index.html
          fi
          
          # Add navigation link back to main page in clubs page  
          if [ -f public/ntu-clubs/index.html ]; then
            sed -i '/<body>/a <a href="../index.html" class="main-nav-link"><i data-lucide="arrow-left"></i><span>Back to Hub</span></a>' public/ntu-clubs/index.html
          fi
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
