# Deploy both static sites to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]          # 默认分支
  workflow_dispatch:            # 手动触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # ---- 打包两个网站 ----
      - name: Build public folder
        run: |
          mkdir public
          # 复制机场指南
          cp -r "Airport Guide/v2"           "public/airport-guide"
          # 复制 C&S Explorer
          cp -r "NTU Clubs & Societies Explorer" "public/ntu-clubs"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public                      # 仅发布 /public

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
